name: 'Test Report'

on:
  workflow_run:
    workflows: ['CI']
    types:
      - completed

jobs:
  report:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion != 'skipped' && github.event.workflow_run.conclusion != 'cancelled' }}
    steps:
    - name: Run git init to work around test reporter bug
      run: git init

    - name: Test Report
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        artifact: test-results
        name: XUnit Tests
        path: '**/*.trx'
        reporter: dotnet-trx
